//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClientSOA.ServiceRefSOA {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfCountry", Namespace="http://tempuri.org/", ItemName="country")]
    [System.SerializableAttribute()]
    public class ArrayOfCountry : System.Collections.Generic.List<ClientSOA.ServiceRefSOA.country> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="country", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class country : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ContinentField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RegionField;
        
        private decimal SurfaceAreaField;
        
        private System.Nullable<short> IndepYearField;
        
        private int PopulationField;
        
        private System.Nullable<decimal> LifeExpectancyField;
        
        private System.Nullable<decimal> GNPField;
        
        private System.Nullable<decimal> GNPOldField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LocalNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string GovernmentFormField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string HeadOfStateField;
        
        private System.Nullable<int> CapitalField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Code2Field;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Code {
            get {
                return this.CodeField;
            }
            set {
                if ((object.ReferenceEquals(this.CodeField, value) != true)) {
                    this.CodeField = value;
                    this.RaisePropertyChanged("Code");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Continent {
            get {
                return this.ContinentField;
            }
            set {
                if ((object.ReferenceEquals(this.ContinentField, value) != true)) {
                    this.ContinentField = value;
                    this.RaisePropertyChanged("Continent");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string Region {
            get {
                return this.RegionField;
            }
            set {
                if ((object.ReferenceEquals(this.RegionField, value) != true)) {
                    this.RegionField = value;
                    this.RaisePropertyChanged("Region");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public decimal SurfaceArea {
            get {
                return this.SurfaceAreaField;
            }
            set {
                if ((this.SurfaceAreaField.Equals(value) != true)) {
                    this.SurfaceAreaField = value;
                    this.RaisePropertyChanged("SurfaceArea");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=5)]
        public System.Nullable<short> IndepYear {
            get {
                return this.IndepYearField;
            }
            set {
                if ((this.IndepYearField.Equals(value) != true)) {
                    this.IndepYearField = value;
                    this.RaisePropertyChanged("IndepYear");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=6)]
        public int Population {
            get {
                return this.PopulationField;
            }
            set {
                if ((this.PopulationField.Equals(value) != true)) {
                    this.PopulationField = value;
                    this.RaisePropertyChanged("Population");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=7)]
        public System.Nullable<decimal> LifeExpectancy {
            get {
                return this.LifeExpectancyField;
            }
            set {
                if ((this.LifeExpectancyField.Equals(value) != true)) {
                    this.LifeExpectancyField = value;
                    this.RaisePropertyChanged("LifeExpectancy");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=8)]
        public System.Nullable<decimal> GNP {
            get {
                return this.GNPField;
            }
            set {
                if ((this.GNPField.Equals(value) != true)) {
                    this.GNPField = value;
                    this.RaisePropertyChanged("GNP");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=9)]
        public System.Nullable<decimal> GNPOld {
            get {
                return this.GNPOldField;
            }
            set {
                if ((this.GNPOldField.Equals(value) != true)) {
                    this.GNPOldField = value;
                    this.RaisePropertyChanged("GNPOld");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=10)]
        public string LocalName {
            get {
                return this.LocalNameField;
            }
            set {
                if ((object.ReferenceEquals(this.LocalNameField, value) != true)) {
                    this.LocalNameField = value;
                    this.RaisePropertyChanged("LocalName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=11)]
        public string GovernmentForm {
            get {
                return this.GovernmentFormField;
            }
            set {
                if ((object.ReferenceEquals(this.GovernmentFormField, value) != true)) {
                    this.GovernmentFormField = value;
                    this.RaisePropertyChanged("GovernmentForm");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=12)]
        public string HeadOfState {
            get {
                return this.HeadOfStateField;
            }
            set {
                if ((object.ReferenceEquals(this.HeadOfStateField, value) != true)) {
                    this.HeadOfStateField = value;
                    this.RaisePropertyChanged("HeadOfState");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=13)]
        public System.Nullable<int> Capital {
            get {
                return this.CapitalField;
            }
            set {
                if ((this.CapitalField.Equals(value) != true)) {
                    this.CapitalField = value;
                    this.RaisePropertyChanged("Capital");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=14)]
        public string Code2 {
            get {
                return this.Code2Field;
            }
            set {
                if ((object.ReferenceEquals(this.Code2Field, value) != true)) {
                    this.Code2Field = value;
                    this.RaisePropertyChanged("Code2");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfCity", Namespace="http://tempuri.org/", ItemName="city")]
    [System.SerializableAttribute()]
    public class ArrayOfCity : System.Collections.Generic.List<ClientSOA.ServiceRefSOA.city> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="city", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class city : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CountryCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DistrictField;
        
        private int PopulationField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string CountryCode {
            get {
                return this.CountryCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.CountryCodeField, value) != true)) {
                    this.CountryCodeField = value;
                    this.RaisePropertyChanged("CountryCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string District {
            get {
                return this.DistrictField;
            }
            set {
                if ((object.ReferenceEquals(this.DistrictField, value) != true)) {
                    this.DistrictField = value;
                    this.RaisePropertyChanged("District");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public int Population {
            get {
                return this.PopulationField;
            }
            set {
                if ((this.PopulationField.Equals(value) != true)) {
                    this.PopulationField = value;
                    this.RaisePropertyChanged("Population");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfCountrylanguage", Namespace="http://tempuri.org/", ItemName="countrylanguage")]
    [System.SerializableAttribute()]
    public class ArrayOfCountrylanguage : System.Collections.Generic.List<ClientSOA.ServiceRefSOA.countrylanguage> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="countrylanguage", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class countrylanguage : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CountryCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LanguageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IsOfficialField;
        
        private decimal PercentageField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string CountryCode {
            get {
                return this.CountryCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.CountryCodeField, value) != true)) {
                    this.CountryCodeField = value;
                    this.RaisePropertyChanged("CountryCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Language {
            get {
                return this.LanguageField;
            }
            set {
                if ((object.ReferenceEquals(this.LanguageField, value) != true)) {
                    this.LanguageField = value;
                    this.RaisePropertyChanged("Language");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string IsOfficial {
            get {
                return this.IsOfficialField;
            }
            set {
                if ((object.ReferenceEquals(this.IsOfficialField, value) != true)) {
                    this.IsOfficialField = value;
                    this.RaisePropertyChanged("IsOfficial");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public decimal Percentage {
            get {
                return this.PercentageField;
            }
            set {
                if ((this.PercentageField.Equals(value) != true)) {
                    this.PercentageField = value;
                    this.RaisePropertyChanged("Percentage");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceRefSOA.MyServicesSoap")]
    public interface MyServicesSoap {
        
        // CODEGEN: Generating message contract since element name HelloWorldResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        ClientSOA.ServiceRefSOA.HelloWorldResponse HelloWorld(ClientSOA.ServiceRefSOA.HelloWorldRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        System.Threading.Tasks.Task<ClientSOA.ServiceRefSOA.HelloWorldResponse> HelloWorldAsync(ClientSOA.ServiceRefSOA.HelloWorldRequest request);
        
        // CODEGEN: Generating message contract since element name getAllCountryResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getAllCountry", ReplyAction="*")]
        ClientSOA.ServiceRefSOA.getAllCountryResponse getAllCountry(ClientSOA.ServiceRefSOA.getAllCountryRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getAllCountry", ReplyAction="*")]
        System.Threading.Tasks.Task<ClientSOA.ServiceRefSOA.getAllCountryResponse> getAllCountryAsync(ClientSOA.ServiceRefSOA.getAllCountryRequest request);
        
        // CODEGEN: Generating message contract since element name code from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getCountryByCode", ReplyAction="*")]
        ClientSOA.ServiceRefSOA.getCountryByCodeResponse getCountryByCode(ClientSOA.ServiceRefSOA.getCountryByCodeRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getCountryByCode", ReplyAction="*")]
        System.Threading.Tasks.Task<ClientSOA.ServiceRefSOA.getCountryByCodeResponse> getCountryByCodeAsync(ClientSOA.ServiceRefSOA.getCountryByCodeRequest request);
        
        // CODEGEN: Generating message contract since element name name from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getCityByName", ReplyAction="*")]
        ClientSOA.ServiceRefSOA.getCityByNameResponse getCityByName(ClientSOA.ServiceRefSOA.getCityByNameRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getCityByName", ReplyAction="*")]
        System.Threading.Tasks.Task<ClientSOA.ServiceRefSOA.getCityByNameResponse> getCityByNameAsync(ClientSOA.ServiceRefSOA.getCityByNameRequest request);
        
        // CODEGEN: Generating message contract since element name country from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getCityBySpecificCountry", ReplyAction="*")]
        ClientSOA.ServiceRefSOA.getCityBySpecificCountryResponse getCityBySpecificCountry(ClientSOA.ServiceRefSOA.getCityBySpecificCountryRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getCityBySpecificCountry", ReplyAction="*")]
        System.Threading.Tasks.Task<ClientSOA.ServiceRefSOA.getCityBySpecificCountryResponse> getCityBySpecificCountryAsync(ClientSOA.ServiceRefSOA.getCityBySpecificCountryRequest request);
        
        // CODEGEN: Generating message contract since element name getAllCountryByPopulationResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getAllCountryByPopulation", ReplyAction="*")]
        ClientSOA.ServiceRefSOA.getAllCountryByPopulationResponse getAllCountryByPopulation(ClientSOA.ServiceRefSOA.getAllCountryByPopulationRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getAllCountryByPopulation", ReplyAction="*")]
        System.Threading.Tasks.Task<ClientSOA.ServiceRefSOA.getAllCountryByPopulationResponse> getAllCountryByPopulationAsync(ClientSOA.ServiceRefSOA.getAllCountryByPopulationRequest request);
        
        // CODEGEN: Generating message contract since element name getAllCountryByGNPResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getAllCountryByGNP", ReplyAction="*")]
        ClientSOA.ServiceRefSOA.getAllCountryByGNPResponse getAllCountryByGNP(ClientSOA.ServiceRefSOA.getAllCountryByGNPRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getAllCountryByGNP", ReplyAction="*")]
        System.Threading.Tasks.Task<ClientSOA.ServiceRefSOA.getAllCountryByGNPResponse> getAllCountryByGNPAsync(ClientSOA.ServiceRefSOA.getAllCountryByGNPRequest request);
        
        // CODEGEN: Generating message contract since element name countryName from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getOfficialLanguageByCountryName", ReplyAction="*")]
        ClientSOA.ServiceRefSOA.getOfficialLanguageByCountryNameResponse getOfficialLanguageByCountryName(ClientSOA.ServiceRefSOA.getOfficialLanguageByCountryNameRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getOfficialLanguageByCountryName", ReplyAction="*")]
        System.Threading.Tasks.Task<ClientSOA.ServiceRefSOA.getOfficialLanguageByCountryNameResponse> getOfficialLanguageByCountryNameAsync(ClientSOA.ServiceRefSOA.getOfficialLanguageByCountryNameRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorld", Namespace="http://tempuri.org/", Order=0)]
        public ClientSOA.ServiceRefSOA.HelloWorldRequestBody Body;
        
        public HelloWorldRequest() {
        }
        
        public HelloWorldRequest(ClientSOA.ServiceRefSOA.HelloWorldRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class HelloWorldRequestBody {
        
        public HelloWorldRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorldResponse", Namespace="http://tempuri.org/", Order=0)]
        public ClientSOA.ServiceRefSOA.HelloWorldResponseBody Body;
        
        public HelloWorldResponse() {
        }
        
        public HelloWorldResponse(ClientSOA.ServiceRefSOA.HelloWorldResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class HelloWorldResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string HelloWorldResult;
        
        public HelloWorldResponseBody() {
        }
        
        public HelloWorldResponseBody(string HelloWorldResult) {
            this.HelloWorldResult = HelloWorldResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getAllCountryRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getAllCountry", Namespace="http://tempuri.org/", Order=0)]
        public ClientSOA.ServiceRefSOA.getAllCountryRequestBody Body;
        
        public getAllCountryRequest() {
        }
        
        public getAllCountryRequest(ClientSOA.ServiceRefSOA.getAllCountryRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class getAllCountryRequestBody {
        
        public getAllCountryRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getAllCountryResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getAllCountryResponse", Namespace="http://tempuri.org/", Order=0)]
        public ClientSOA.ServiceRefSOA.getAllCountryResponseBody Body;
        
        public getAllCountryResponse() {
        }
        
        public getAllCountryResponse(ClientSOA.ServiceRefSOA.getAllCountryResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class getAllCountryResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ClientSOA.ServiceRefSOA.ArrayOfCountry getAllCountryResult;
        
        public getAllCountryResponseBody() {
        }
        
        public getAllCountryResponseBody(ClientSOA.ServiceRefSOA.ArrayOfCountry getAllCountryResult) {
            this.getAllCountryResult = getAllCountryResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getCountryByCodeRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getCountryByCode", Namespace="http://tempuri.org/", Order=0)]
        public ClientSOA.ServiceRefSOA.getCountryByCodeRequestBody Body;
        
        public getCountryByCodeRequest() {
        }
        
        public getCountryByCodeRequest(ClientSOA.ServiceRefSOA.getCountryByCodeRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class getCountryByCodeRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string code;
        
        public getCountryByCodeRequestBody() {
        }
        
        public getCountryByCodeRequestBody(string code) {
            this.code = code;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getCountryByCodeResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getCountryByCodeResponse", Namespace="http://tempuri.org/", Order=0)]
        public ClientSOA.ServiceRefSOA.getCountryByCodeResponseBody Body;
        
        public getCountryByCodeResponse() {
        }
        
        public getCountryByCodeResponse(ClientSOA.ServiceRefSOA.getCountryByCodeResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class getCountryByCodeResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ClientSOA.ServiceRefSOA.ArrayOfCountry getCountryByCodeResult;
        
        public getCountryByCodeResponseBody() {
        }
        
        public getCountryByCodeResponseBody(ClientSOA.ServiceRefSOA.ArrayOfCountry getCountryByCodeResult) {
            this.getCountryByCodeResult = getCountryByCodeResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getCityByNameRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getCityByName", Namespace="http://tempuri.org/", Order=0)]
        public ClientSOA.ServiceRefSOA.getCityByNameRequestBody Body;
        
        public getCityByNameRequest() {
        }
        
        public getCityByNameRequest(ClientSOA.ServiceRefSOA.getCityByNameRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class getCityByNameRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string name;
        
        public getCityByNameRequestBody() {
        }
        
        public getCityByNameRequestBody(string name) {
            this.name = name;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getCityByNameResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getCityByNameResponse", Namespace="http://tempuri.org/", Order=0)]
        public ClientSOA.ServiceRefSOA.getCityByNameResponseBody Body;
        
        public getCityByNameResponse() {
        }
        
        public getCityByNameResponse(ClientSOA.ServiceRefSOA.getCityByNameResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class getCityByNameResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ClientSOA.ServiceRefSOA.ArrayOfCity getCityByNameResult;
        
        public getCityByNameResponseBody() {
        }
        
        public getCityByNameResponseBody(ClientSOA.ServiceRefSOA.ArrayOfCity getCityByNameResult) {
            this.getCityByNameResult = getCityByNameResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getCityBySpecificCountryRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getCityBySpecificCountry", Namespace="http://tempuri.org/", Order=0)]
        public ClientSOA.ServiceRefSOA.getCityBySpecificCountryRequestBody Body;
        
        public getCityBySpecificCountryRequest() {
        }
        
        public getCityBySpecificCountryRequest(ClientSOA.ServiceRefSOA.getCityBySpecificCountryRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class getCityBySpecificCountryRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string country;
        
        public getCityBySpecificCountryRequestBody() {
        }
        
        public getCityBySpecificCountryRequestBody(string country) {
            this.country = country;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getCityBySpecificCountryResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getCityBySpecificCountryResponse", Namespace="http://tempuri.org/", Order=0)]
        public ClientSOA.ServiceRefSOA.getCityBySpecificCountryResponseBody Body;
        
        public getCityBySpecificCountryResponse() {
        }
        
        public getCityBySpecificCountryResponse(ClientSOA.ServiceRefSOA.getCityBySpecificCountryResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class getCityBySpecificCountryResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ClientSOA.ServiceRefSOA.ArrayOfCity getCityBySpecificCountryResult;
        
        public getCityBySpecificCountryResponseBody() {
        }
        
        public getCityBySpecificCountryResponseBody(ClientSOA.ServiceRefSOA.ArrayOfCity getCityBySpecificCountryResult) {
            this.getCityBySpecificCountryResult = getCityBySpecificCountryResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getAllCountryByPopulationRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getAllCountryByPopulation", Namespace="http://tempuri.org/", Order=0)]
        public ClientSOA.ServiceRefSOA.getAllCountryByPopulationRequestBody Body;
        
        public getAllCountryByPopulationRequest() {
        }
        
        public getAllCountryByPopulationRequest(ClientSOA.ServiceRefSOA.getAllCountryByPopulationRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class getAllCountryByPopulationRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int population;
        
        public getAllCountryByPopulationRequestBody() {
        }
        
        public getAllCountryByPopulationRequestBody(int population) {
            this.population = population;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getAllCountryByPopulationResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getAllCountryByPopulationResponse", Namespace="http://tempuri.org/", Order=0)]
        public ClientSOA.ServiceRefSOA.getAllCountryByPopulationResponseBody Body;
        
        public getAllCountryByPopulationResponse() {
        }
        
        public getAllCountryByPopulationResponse(ClientSOA.ServiceRefSOA.getAllCountryByPopulationResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class getAllCountryByPopulationResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ClientSOA.ServiceRefSOA.ArrayOfCountry getAllCountryByPopulationResult;
        
        public getAllCountryByPopulationResponseBody() {
        }
        
        public getAllCountryByPopulationResponseBody(ClientSOA.ServiceRefSOA.ArrayOfCountry getAllCountryByPopulationResult) {
            this.getAllCountryByPopulationResult = getAllCountryByPopulationResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getAllCountryByGNPRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getAllCountryByGNP", Namespace="http://tempuri.org/", Order=0)]
        public ClientSOA.ServiceRefSOA.getAllCountryByGNPRequestBody Body;
        
        public getAllCountryByGNPRequest() {
        }
        
        public getAllCountryByGNPRequest(ClientSOA.ServiceRefSOA.getAllCountryByGNPRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class getAllCountryByGNPRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public decimal GNP;
        
        public getAllCountryByGNPRequestBody() {
        }
        
        public getAllCountryByGNPRequestBody(decimal GNP) {
            this.GNP = GNP;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getAllCountryByGNPResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getAllCountryByGNPResponse", Namespace="http://tempuri.org/", Order=0)]
        public ClientSOA.ServiceRefSOA.getAllCountryByGNPResponseBody Body;
        
        public getAllCountryByGNPResponse() {
        }
        
        public getAllCountryByGNPResponse(ClientSOA.ServiceRefSOA.getAllCountryByGNPResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class getAllCountryByGNPResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ClientSOA.ServiceRefSOA.ArrayOfCountry getAllCountryByGNPResult;
        
        public getAllCountryByGNPResponseBody() {
        }
        
        public getAllCountryByGNPResponseBody(ClientSOA.ServiceRefSOA.ArrayOfCountry getAllCountryByGNPResult) {
            this.getAllCountryByGNPResult = getAllCountryByGNPResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getOfficialLanguageByCountryNameRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getOfficialLanguageByCountryName", Namespace="http://tempuri.org/", Order=0)]
        public ClientSOA.ServiceRefSOA.getOfficialLanguageByCountryNameRequestBody Body;
        
        public getOfficialLanguageByCountryNameRequest() {
        }
        
        public getOfficialLanguageByCountryNameRequest(ClientSOA.ServiceRefSOA.getOfficialLanguageByCountryNameRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class getOfficialLanguageByCountryNameRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string countryName;
        
        public getOfficialLanguageByCountryNameRequestBody() {
        }
        
        public getOfficialLanguageByCountryNameRequestBody(string countryName) {
            this.countryName = countryName;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getOfficialLanguageByCountryNameResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getOfficialLanguageByCountryNameResponse", Namespace="http://tempuri.org/", Order=0)]
        public ClientSOA.ServiceRefSOA.getOfficialLanguageByCountryNameResponseBody Body;
        
        public getOfficialLanguageByCountryNameResponse() {
        }
        
        public getOfficialLanguageByCountryNameResponse(ClientSOA.ServiceRefSOA.getOfficialLanguageByCountryNameResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class getOfficialLanguageByCountryNameResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ClientSOA.ServiceRefSOA.ArrayOfCountrylanguage getOfficialLanguageByCountryNameResult;
        
        public getOfficialLanguageByCountryNameResponseBody() {
        }
        
        public getOfficialLanguageByCountryNameResponseBody(ClientSOA.ServiceRefSOA.ArrayOfCountrylanguage getOfficialLanguageByCountryNameResult) {
            this.getOfficialLanguageByCountryNameResult = getOfficialLanguageByCountryNameResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface MyServicesSoapChannel : ClientSOA.ServiceRefSOA.MyServicesSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MyServicesSoapClient : System.ServiceModel.ClientBase<ClientSOA.ServiceRefSOA.MyServicesSoap>, ClientSOA.ServiceRefSOA.MyServicesSoap {
        
        public MyServicesSoapClient() {
        }
        
        public MyServicesSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public MyServicesSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MyServicesSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MyServicesSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ClientSOA.ServiceRefSOA.HelloWorldResponse ClientSOA.ServiceRefSOA.MyServicesSoap.HelloWorld(ClientSOA.ServiceRefSOA.HelloWorldRequest request) {
            return base.Channel.HelloWorld(request);
        }
        
        public string HelloWorld() {
            ClientSOA.ServiceRefSOA.HelloWorldRequest inValue = new ClientSOA.ServiceRefSOA.HelloWorldRequest();
            inValue.Body = new ClientSOA.ServiceRefSOA.HelloWorldRequestBody();
            ClientSOA.ServiceRefSOA.HelloWorldResponse retVal = ((ClientSOA.ServiceRefSOA.MyServicesSoap)(this)).HelloWorld(inValue);
            return retVal.Body.HelloWorldResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ClientSOA.ServiceRefSOA.HelloWorldResponse> ClientSOA.ServiceRefSOA.MyServicesSoap.HelloWorldAsync(ClientSOA.ServiceRefSOA.HelloWorldRequest request) {
            return base.Channel.HelloWorldAsync(request);
        }
        
        public System.Threading.Tasks.Task<ClientSOA.ServiceRefSOA.HelloWorldResponse> HelloWorldAsync() {
            ClientSOA.ServiceRefSOA.HelloWorldRequest inValue = new ClientSOA.ServiceRefSOA.HelloWorldRequest();
            inValue.Body = new ClientSOA.ServiceRefSOA.HelloWorldRequestBody();
            return ((ClientSOA.ServiceRefSOA.MyServicesSoap)(this)).HelloWorldAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ClientSOA.ServiceRefSOA.getAllCountryResponse ClientSOA.ServiceRefSOA.MyServicesSoap.getAllCountry(ClientSOA.ServiceRefSOA.getAllCountryRequest request) {
            return base.Channel.getAllCountry(request);
        }
        
        public ClientSOA.ServiceRefSOA.ArrayOfCountry getAllCountry() {
            ClientSOA.ServiceRefSOA.getAllCountryRequest inValue = new ClientSOA.ServiceRefSOA.getAllCountryRequest();
            inValue.Body = new ClientSOA.ServiceRefSOA.getAllCountryRequestBody();
            ClientSOA.ServiceRefSOA.getAllCountryResponse retVal = ((ClientSOA.ServiceRefSOA.MyServicesSoap)(this)).getAllCountry(inValue);
            return retVal.Body.getAllCountryResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ClientSOA.ServiceRefSOA.getAllCountryResponse> ClientSOA.ServiceRefSOA.MyServicesSoap.getAllCountryAsync(ClientSOA.ServiceRefSOA.getAllCountryRequest request) {
            return base.Channel.getAllCountryAsync(request);
        }
        
        public System.Threading.Tasks.Task<ClientSOA.ServiceRefSOA.getAllCountryResponse> getAllCountryAsync() {
            ClientSOA.ServiceRefSOA.getAllCountryRequest inValue = new ClientSOA.ServiceRefSOA.getAllCountryRequest();
            inValue.Body = new ClientSOA.ServiceRefSOA.getAllCountryRequestBody();
            return ((ClientSOA.ServiceRefSOA.MyServicesSoap)(this)).getAllCountryAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ClientSOA.ServiceRefSOA.getCountryByCodeResponse ClientSOA.ServiceRefSOA.MyServicesSoap.getCountryByCode(ClientSOA.ServiceRefSOA.getCountryByCodeRequest request) {
            return base.Channel.getCountryByCode(request);
        }
        
        public ClientSOA.ServiceRefSOA.ArrayOfCountry getCountryByCode(string code) {
            ClientSOA.ServiceRefSOA.getCountryByCodeRequest inValue = new ClientSOA.ServiceRefSOA.getCountryByCodeRequest();
            inValue.Body = new ClientSOA.ServiceRefSOA.getCountryByCodeRequestBody();
            inValue.Body.code = code;
            ClientSOA.ServiceRefSOA.getCountryByCodeResponse retVal = ((ClientSOA.ServiceRefSOA.MyServicesSoap)(this)).getCountryByCode(inValue);
            return retVal.Body.getCountryByCodeResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ClientSOA.ServiceRefSOA.getCountryByCodeResponse> ClientSOA.ServiceRefSOA.MyServicesSoap.getCountryByCodeAsync(ClientSOA.ServiceRefSOA.getCountryByCodeRequest request) {
            return base.Channel.getCountryByCodeAsync(request);
        }
        
        public System.Threading.Tasks.Task<ClientSOA.ServiceRefSOA.getCountryByCodeResponse> getCountryByCodeAsync(string code) {
            ClientSOA.ServiceRefSOA.getCountryByCodeRequest inValue = new ClientSOA.ServiceRefSOA.getCountryByCodeRequest();
            inValue.Body = new ClientSOA.ServiceRefSOA.getCountryByCodeRequestBody();
            inValue.Body.code = code;
            return ((ClientSOA.ServiceRefSOA.MyServicesSoap)(this)).getCountryByCodeAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ClientSOA.ServiceRefSOA.getCityByNameResponse ClientSOA.ServiceRefSOA.MyServicesSoap.getCityByName(ClientSOA.ServiceRefSOA.getCityByNameRequest request) {
            return base.Channel.getCityByName(request);
        }
        
        public ClientSOA.ServiceRefSOA.ArrayOfCity getCityByName(string name) {
            ClientSOA.ServiceRefSOA.getCityByNameRequest inValue = new ClientSOA.ServiceRefSOA.getCityByNameRequest();
            inValue.Body = new ClientSOA.ServiceRefSOA.getCityByNameRequestBody();
            inValue.Body.name = name;
            ClientSOA.ServiceRefSOA.getCityByNameResponse retVal = ((ClientSOA.ServiceRefSOA.MyServicesSoap)(this)).getCityByName(inValue);
            return retVal.Body.getCityByNameResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ClientSOA.ServiceRefSOA.getCityByNameResponse> ClientSOA.ServiceRefSOA.MyServicesSoap.getCityByNameAsync(ClientSOA.ServiceRefSOA.getCityByNameRequest request) {
            return base.Channel.getCityByNameAsync(request);
        }
        
        public System.Threading.Tasks.Task<ClientSOA.ServiceRefSOA.getCityByNameResponse> getCityByNameAsync(string name) {
            ClientSOA.ServiceRefSOA.getCityByNameRequest inValue = new ClientSOA.ServiceRefSOA.getCityByNameRequest();
            inValue.Body = new ClientSOA.ServiceRefSOA.getCityByNameRequestBody();
            inValue.Body.name = name;
            return ((ClientSOA.ServiceRefSOA.MyServicesSoap)(this)).getCityByNameAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ClientSOA.ServiceRefSOA.getCityBySpecificCountryResponse ClientSOA.ServiceRefSOA.MyServicesSoap.getCityBySpecificCountry(ClientSOA.ServiceRefSOA.getCityBySpecificCountryRequest request) {
            return base.Channel.getCityBySpecificCountry(request);
        }
        
        public ClientSOA.ServiceRefSOA.ArrayOfCity getCityBySpecificCountry(string country) {
            ClientSOA.ServiceRefSOA.getCityBySpecificCountryRequest inValue = new ClientSOA.ServiceRefSOA.getCityBySpecificCountryRequest();
            inValue.Body = new ClientSOA.ServiceRefSOA.getCityBySpecificCountryRequestBody();
            inValue.Body.country = country;
            ClientSOA.ServiceRefSOA.getCityBySpecificCountryResponse retVal = ((ClientSOA.ServiceRefSOA.MyServicesSoap)(this)).getCityBySpecificCountry(inValue);
            return retVal.Body.getCityBySpecificCountryResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ClientSOA.ServiceRefSOA.getCityBySpecificCountryResponse> ClientSOA.ServiceRefSOA.MyServicesSoap.getCityBySpecificCountryAsync(ClientSOA.ServiceRefSOA.getCityBySpecificCountryRequest request) {
            return base.Channel.getCityBySpecificCountryAsync(request);
        }
        
        public System.Threading.Tasks.Task<ClientSOA.ServiceRefSOA.getCityBySpecificCountryResponse> getCityBySpecificCountryAsync(string country) {
            ClientSOA.ServiceRefSOA.getCityBySpecificCountryRequest inValue = new ClientSOA.ServiceRefSOA.getCityBySpecificCountryRequest();
            inValue.Body = new ClientSOA.ServiceRefSOA.getCityBySpecificCountryRequestBody();
            inValue.Body.country = country;
            return ((ClientSOA.ServiceRefSOA.MyServicesSoap)(this)).getCityBySpecificCountryAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ClientSOA.ServiceRefSOA.getAllCountryByPopulationResponse ClientSOA.ServiceRefSOA.MyServicesSoap.getAllCountryByPopulation(ClientSOA.ServiceRefSOA.getAllCountryByPopulationRequest request) {
            return base.Channel.getAllCountryByPopulation(request);
        }
        
        public ClientSOA.ServiceRefSOA.ArrayOfCountry getAllCountryByPopulation(int population) {
            ClientSOA.ServiceRefSOA.getAllCountryByPopulationRequest inValue = new ClientSOA.ServiceRefSOA.getAllCountryByPopulationRequest();
            inValue.Body = new ClientSOA.ServiceRefSOA.getAllCountryByPopulationRequestBody();
            inValue.Body.population = population;
            ClientSOA.ServiceRefSOA.getAllCountryByPopulationResponse retVal = ((ClientSOA.ServiceRefSOA.MyServicesSoap)(this)).getAllCountryByPopulation(inValue);
            return retVal.Body.getAllCountryByPopulationResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ClientSOA.ServiceRefSOA.getAllCountryByPopulationResponse> ClientSOA.ServiceRefSOA.MyServicesSoap.getAllCountryByPopulationAsync(ClientSOA.ServiceRefSOA.getAllCountryByPopulationRequest request) {
            return base.Channel.getAllCountryByPopulationAsync(request);
        }
        
        public System.Threading.Tasks.Task<ClientSOA.ServiceRefSOA.getAllCountryByPopulationResponse> getAllCountryByPopulationAsync(int population) {
            ClientSOA.ServiceRefSOA.getAllCountryByPopulationRequest inValue = new ClientSOA.ServiceRefSOA.getAllCountryByPopulationRequest();
            inValue.Body = new ClientSOA.ServiceRefSOA.getAllCountryByPopulationRequestBody();
            inValue.Body.population = population;
            return ((ClientSOA.ServiceRefSOA.MyServicesSoap)(this)).getAllCountryByPopulationAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ClientSOA.ServiceRefSOA.getAllCountryByGNPResponse ClientSOA.ServiceRefSOA.MyServicesSoap.getAllCountryByGNP(ClientSOA.ServiceRefSOA.getAllCountryByGNPRequest request) {
            return base.Channel.getAllCountryByGNP(request);
        }
        
        public ClientSOA.ServiceRefSOA.ArrayOfCountry getAllCountryByGNP(decimal GNP) {
            ClientSOA.ServiceRefSOA.getAllCountryByGNPRequest inValue = new ClientSOA.ServiceRefSOA.getAllCountryByGNPRequest();
            inValue.Body = new ClientSOA.ServiceRefSOA.getAllCountryByGNPRequestBody();
            inValue.Body.GNP = GNP;
            ClientSOA.ServiceRefSOA.getAllCountryByGNPResponse retVal = ((ClientSOA.ServiceRefSOA.MyServicesSoap)(this)).getAllCountryByGNP(inValue);
            return retVal.Body.getAllCountryByGNPResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ClientSOA.ServiceRefSOA.getAllCountryByGNPResponse> ClientSOA.ServiceRefSOA.MyServicesSoap.getAllCountryByGNPAsync(ClientSOA.ServiceRefSOA.getAllCountryByGNPRequest request) {
            return base.Channel.getAllCountryByGNPAsync(request);
        }
        
        public System.Threading.Tasks.Task<ClientSOA.ServiceRefSOA.getAllCountryByGNPResponse> getAllCountryByGNPAsync(decimal GNP) {
            ClientSOA.ServiceRefSOA.getAllCountryByGNPRequest inValue = new ClientSOA.ServiceRefSOA.getAllCountryByGNPRequest();
            inValue.Body = new ClientSOA.ServiceRefSOA.getAllCountryByGNPRequestBody();
            inValue.Body.GNP = GNP;
            return ((ClientSOA.ServiceRefSOA.MyServicesSoap)(this)).getAllCountryByGNPAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ClientSOA.ServiceRefSOA.getOfficialLanguageByCountryNameResponse ClientSOA.ServiceRefSOA.MyServicesSoap.getOfficialLanguageByCountryName(ClientSOA.ServiceRefSOA.getOfficialLanguageByCountryNameRequest request) {
            return base.Channel.getOfficialLanguageByCountryName(request);
        }
        
        public ClientSOA.ServiceRefSOA.ArrayOfCountrylanguage getOfficialLanguageByCountryName(string countryName) {
            ClientSOA.ServiceRefSOA.getOfficialLanguageByCountryNameRequest inValue = new ClientSOA.ServiceRefSOA.getOfficialLanguageByCountryNameRequest();
            inValue.Body = new ClientSOA.ServiceRefSOA.getOfficialLanguageByCountryNameRequestBody();
            inValue.Body.countryName = countryName;
            ClientSOA.ServiceRefSOA.getOfficialLanguageByCountryNameResponse retVal = ((ClientSOA.ServiceRefSOA.MyServicesSoap)(this)).getOfficialLanguageByCountryName(inValue);
            return retVal.Body.getOfficialLanguageByCountryNameResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ClientSOA.ServiceRefSOA.getOfficialLanguageByCountryNameResponse> ClientSOA.ServiceRefSOA.MyServicesSoap.getOfficialLanguageByCountryNameAsync(ClientSOA.ServiceRefSOA.getOfficialLanguageByCountryNameRequest request) {
            return base.Channel.getOfficialLanguageByCountryNameAsync(request);
        }
        
        public System.Threading.Tasks.Task<ClientSOA.ServiceRefSOA.getOfficialLanguageByCountryNameResponse> getOfficialLanguageByCountryNameAsync(string countryName) {
            ClientSOA.ServiceRefSOA.getOfficialLanguageByCountryNameRequest inValue = new ClientSOA.ServiceRefSOA.getOfficialLanguageByCountryNameRequest();
            inValue.Body = new ClientSOA.ServiceRefSOA.getOfficialLanguageByCountryNameRequestBody();
            inValue.Body.countryName = countryName;
            return ((ClientSOA.ServiceRefSOA.MyServicesSoap)(this)).getOfficialLanguageByCountryNameAsync(inValue);
        }
    }
}
